Feature price list
CrystallizeAPI/superfast-boilerplates pull request #4
Opened 2023-02-10 17:07 UTC by dhairyadwivedi

| Q             | A            |
| ------------- | ------------ |
| Branch?       | main / feature-price-list
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Fixed tickets | [sc-8806]

2023-02-12 22:27 UTC, Plopix requested changes

2023-02-12 22:27 UTC, Plopix commented on frameworks/remix-run/application/src/routes/$langstore/index.tsx
> +import { getMarketIdentifier } from '~/ui/lib/marketIdentifier';
move into `use-cases`

2023-02-12 22:27 UTC, Plopix commented on frameworks/remix-run/application/src/routes/$langstore/index.tsx
> +    const data = await dataFetcherForShapePage('landing-page', path, requestContext, params, getMarketIdentifier(user));
`getMarketIdentifier` => `marketIdentifiersForUser`

2023-02-12 22:27 UTC, Plopix commented on frameworks/remix-run/application/src/routes/$langstore/shop/$folder.$product.tsx
> +import { getMarketIdentifier } from '~/ui/lib/marketIdentifier';
marketIdentifiersForUser

2023-02-12 22:27 UTC, Plopix commented on shared/application/use-cases/crystallize/read/fetchDocument.ts
> +    marketIdentifier?: string,
```suggestion
    marketIdentifiers?: string[],
```

2023-02-12 22:27 UTC, Plopix commented on shared/application/use-cases/crystallize/read/fetchFolder.ts
> +    marketIdentifier?: string,
```suggestion
    marketIdentifiers?: string[],
```

2023-02-12 22:27 UTC, Plopix commented on shared/application/use-cases/crystallize/read/fetchFolderWithChildren.ts
> +    marketIdentifier?: string,
```suggestion
    marketIdentifiers?: string[],
```

2023-02-12 22:27 UTC, Plopix commented on shared/application/use-cases/crystallize/read/fetchHierarchy.ts
> +export default async (apiClient: ClientInterface, path: string, language: string, marketIdentifier?: string) => {
```
    marketIdentifiers?: string[],
```

2023-02-12 22:27 UTC, Plopix commented on shared/application/use-cases/crystallize/read/fetchLandingPage.ts
> +    marketIdentifier?: string,
```suggestion
    marketIdentifiers?: string[],
```

2023-02-12 22:27 UTC, Plopix commented on shared/application/use-cases/crystallize/read/fetchProduct.ts
> +    marketIdentifier?: string,
```suggestion
    marketIdentifiers?: string[],
```

2023-02-12 22:27 UTC, Plopix commented on shared/application/use-cases/dataFetcherForShapePage.server.ts
> +    marketIdentifier?: string,
```suggestion
    marketIdentifiers?: string[],
```

2023-02-13 11:36 UTC, dhairyadwivedi commented on shared/application/use-cases/checkout/cart.ts
> +        if (variant?.priceFor?.price && variant?.priceFor?.price < variant?.price!) {
Tests are failing once this is removed

2023-02-13 11:37 UTC, dhairyadwivedi commented on shared/application/use-cases/checkout/cart.ts
> +        if (variant?.priceFor?.price && variant?.priceFor?.price < variant?.price!) {
Tests are failing if this is removed

2023-02-13 21:13 UTC, merged